// iot-uni-app/components/safety/SafetyView.vue
<template>
  <view class="safety-view">
    <view v-if="!devices.length" class="safety-view__empty">
      <app-icon name="shield" :size="36" color="#cbd5e1" />
      <text class="safety-view__empty-text">请先添加设备以开启安全监控</text>
    </view>

    <template v-else>
      <view class="safety-view__header">
        <view>
          <text class="safety-view__title">安全中心</text>
          <text class="safety-view__subtitle">实时监控全屋厨房安全</text>
        </view>

        <view class="safety-view__dropdown-wrap" v-if="devices.length > 1">
          <view class="safety-view__dropdown-btn" @tap="dropdownOpen = !dropdownOpen">
            <text class="safety-view__dropdown-text line-clamp-1">{{ currentDevice ? currentDevice.name : '' }}</text>
            <app-icon name="chevron" :size="14" color="#94a3b8" />
          </view>

          <view class="safety-view__dropdown" v-if="dropdownOpen">
            <view class="safety-view__dropdown-overlay" @tap="dropdownOpen = false"></view>
            <view class="safety-view__dropdown-panel">
              <view v-if="myDevices.length">
                <text class="safety-view__dropdown-kicker">我的设备</text>
                <view
                  v-for="device in myDevices"
                  :key="device.id"
                  class="safety-view__dropdown-item"
                  :class="{ 'safety-view__dropdown-item--active': selectedDeviceId === device.id }"
                  @tap="selectDevice(device.id)"
                >
                  <text class="line-clamp-1">{{ device.name }}</text>
                  <app-icon v-if="selectedDeviceId === device.id" name="check" :size="12" color="#f97316" />
                </view>
              </view>

              <view v-if="sharedDevices.length">
                <text class="safety-view__dropdown-kicker">共享设备</text>
                <view
                  v-for="device in sharedDevices"
                  :key="device.id"
                  class="safety-view__dropdown-item"
                  :class="{ 'safety-view__dropdown-item--active': selectedDeviceId === device.id }"
                  @tap="selectDevice(device.id)"
                >
                  <text class="line-clamp-1">{{ device.name }}</text>
                  <app-icon v-if="selectedDeviceId === device.id" name="check" :size="12" color="#f97316" />
                </view>
              </view>
            </view>
          </view>
        </view>
      </view>

      <card-box custom-style="border:0; padding:16px;" :class="currentDevice && currentDevice.isOn ? 'safety-view__score--on' : 'safety-view__score--off'">
        <view class="safety-view__score">
          <view>
            <text class="safety-view__score-label">当前安全评分</text>
            <text class="safety-view__score-value">{{ currentDevice && currentDevice.isOn ? '98' : '--' }}</text>
          </view>
          <view class="safety-view__score-icon">
            <app-icon name="shield" :size="24" color="#ffffff" />
          </view>
        </view>
        <view class="safety-view__score-foot">
          <text class="safety-view__score-copy">
            {{ currentDevice && currentDevice.isOn ? '所有传感器运行正常' : '设备待机中，基础监测仍保持开启' }}
          </text>
          <text class="safety-view__score-link">查看报告</text>
        </view>
      </card-box>

      <view class="safety-view__sensor-grid">
        <card-box v-for="sensor in sensors" :key="sensor.id" custom-style="padding:12px;">
          <view class="safety-view__sensor-top">
            <view class="safety-view__sensor-icon" :class="`safety-view__sensor-icon--${sensor.status}`">
              <app-icon :name="sensor.icon" :size="16" :color="sensor.status === 'safe' ? '#10b981' : sensor.status === 'warning' ? '#f59e0b' : '#f43f5e'" />
            </view>
            <view class="safety-view__sensor-dot" :class="`safety-view__sensor-dot--${sensor.status}`"></view>
          </view>
          <text class="safety-view__sensor-label">{{ sensor.label }}</text>
          <text class="safety-view__sensor-value">{{ sensor.value }}</text>
        </card-box>
      </view>

      <card-box custom-style="padding:0; overflow:hidden;">
        <view class="safety-view__log-head">
          <text class="safety-view__log-title">告警记录</text>
          <app-icon name="alert" :size="14" color="#f43f5e" />
        </view>
        <view v-if="!alertLogs.length" class="safety-view__log-empty">
          <text class="safety-view__log-empty-text">暂无告警记录</text>
        </view>
        <view v-else>
          <view v-for="log in alertLogs" :key="log.id" class="safety-view__log-row">
            <view class="safety-view__log-dot" :class="log.type === 'warning' ? 'safety-view__log-dot--warning' : 'safety-view__log-dot--danger'"></view>
            <view class="safety-view__log-copy">
              <text class="safety-view__log-event">{{ log.event }}</text>
              <text class="safety-view__log-time">{{ log.time }}</text>
            </view>
          </view>
        </view>
      </card-box>

      <card-box custom-style="padding:0; overflow:hidden; margin-top:16px;">
        <view class="safety-view__log-head">
          <text class="safety-view__log-title">操作记录</text>
          <app-icon name="history" :size="14" color="#94a3b8" />
        </view>
        <view v-if="!logs.length" class="safety-view__log-empty">
          <text class="safety-view__log-empty-text">暂无操作记录</text>
        </view>
        <view v-else>
          <view v-for="log in logs" :key="log.id" class="safety-view__log-row">
            <view class="safety-view__log-dot" :class="dotClass(log.type)"></view>
            <view class="safety-view__log-copy">
              <text class="safety-view__log-event">{{ log.event }}</text>
              <text class="safety-view__log-time">{{ formatDate(log.createdAt) }}</text>
            </view>
          </view>
        </view>
      </card-box>
    </template>
  </view>
</template>

<script setup>
import AppIcon from '../ui/AppIcon.vue'
import CardBox from '../ui/CardBox.vue'
import { useSafetyController } from '../../services/features/safety/safety-controller'

const props = defineProps({
  devices: {
    type: Array,
    default: () => [],
  },
  user: {
    type: Object,
    default: null,
  },
})

const {
  selectedDeviceId,
  dropdownOpen,
  logs,
  currentDevice,
  myDevices,
  sharedDevices,
  alertLogs,
  sensors,
  selectDevice,
  dotClass,
  formatDate,
} = useSafetyController({
  props,
})
</script>

<style scoped>
.safety-view__empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 80px 0;
}

.safety-view__empty-text {
  margin-top: 14px;
  font-size: 14px;
  color: #94a3b8;
}

.safety-view__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 20px;
}

.safety-view__title {
  display: block;
  font-size: 20px;
  font-weight: 700;
  font-family: 'Outfit', sans-serif;
  color: #0f172a;
}

.safety-view__subtitle {
  display: block;
  margin-top: 6px;
  font-size: 10px;
  color: #64748b;
}

.safety-view__dropdown-wrap {
  position: relative;
}

.safety-view__dropdown-btn {
  display: flex;
  align-items: center;
  justify-content: space-between;
  min-width: 120px;
  max-width: 148px;
  min-height: 40px;
  padding: 0 14px;
  background: #ffffff;
  border: 1px solid #e2e8f0;
  border-radius: 16px;
}

.safety-view__dropdown-text {
  max-width: 92px;
  font-size: 12px;
  font-weight: 700;
  color: #334155;
}

.safety-view__dropdown {
  position: absolute;
  top: 48px;
  right: 0;
  z-index: 40;
}

.safety-view__dropdown-overlay {
  position: fixed;
  inset: 0;
}

.safety-view__dropdown-panel {
  position: relative;
  width: 224px;
  max-height: 300px;
  padding: 10px;
  overflow: hidden;
  background: #ffffff;
  border: 1px solid #f1f5f9;
  border-radius: 20px;
  box-shadow: 0 18px 40px rgba(15, 23, 42, 0.12);
}

.safety-view__dropdown-kicker {
  display: block;
  padding: 8px 10px;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 1px;
  color: #94a3b8;
  text-transform: uppercase;
}

.safety-view__dropdown-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  min-height: 40px;
  padding: 0 12px;
  border-radius: 14px;
  font-size: 12px;
  font-weight: 700;
  color: #475569;
}

.safety-view__dropdown-item--active {
  background: #fff7ed;
  color: #f97316;
}

.safety-view__score--on {
  background: #10b981;
}

.safety-view__score--off {
  background: #334155;
}

.safety-view__score {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.safety-view__score-label {
  display: block;
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 1px;
  color: rgba(255, 255, 255, 0.72);
  text-transform: uppercase;
}

.safety-view__score-value {
  display: block;
  margin-top: 8px;
  font-size: 44px;
  font-weight: 700;
  color: #ffffff;
}

.safety-view__score-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 64px;
  height: 64px;
  background: rgba(255, 255, 255, 0.18);
  border-radius: 32px;
}

.safety-view__score-foot {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-top: 18px;
  padding-top: 18px;
  border-top: 1px solid rgba(255, 255, 255, 0.12);
}

.safety-view__score-copy,
.safety-view__score-link {
  font-size: 11px;
  color: #ffffff;
}

.safety-view__score-link {
  text-decoration: underline;
}

.safety-view__sensor-grid {
  display: flex;
  flex-wrap: wrap;
  margin: 16px -6px 0;
}

.safety-view__sensor-grid .card-box {
  width: calc(50% - 12px);
  margin: 6px;
}

.safety-view__sensor-top {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.safety-view__sensor-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: 12px;
}

.safety-view__sensor-icon--safe {
  background: #ecfdf5;
}

.safety-view__sensor-icon--warning {
  background: #fffbeb;
}

.safety-view__sensor-icon--danger {
  background: #fff1f2;
}

.safety-view__sensor-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
}

.safety-view__sensor-dot--safe {
  background: #10b981;
}

.safety-view__sensor-dot--warning {
  background: #f59e0b;
}

.safety-view__sensor-dot--danger {
  background: #f43f5e;
}

.safety-view__sensor-label {
  display: block;
  margin-top: 12px;
  font-size: 11px;
  color: #94a3b8;
}

.safety-view__sensor-value {
  display: block;
  margin-top: 6px;
  font-size: 15px;
  font-weight: 700;
  color: #0f172a;
}

.safety-view__log-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px;
  border-bottom: 1px solid #f1f5f9;
}

.safety-view__log-title {
  font-size: 14px;
  font-weight: 700;
  color: #0f172a;
}

.safety-view__log-empty {
  padding: 30px 0;
  text-align: center;
}

.safety-view__log-empty-text {
  font-size: 12px;
  color: #94a3b8;
}

.safety-view__log-row {
  display: flex;
  align-items: flex-start;
  padding: 14px 16px;
}

.safety-view__log-row + .safety-view__log-row {
  border-top: 1px solid #f8fafc;
}

.safety-view__log-dot {
  width: 8px;
  height: 8px;
  margin-top: 6px;
  border-radius: 50%;
}

.safety-view__log-dot--warning {
  background: #f59e0b;
}

.safety-view__log-dot--danger {
  background: #f43f5e;
}

.safety-view__log-dot--success {
  background: #10b981;
}

.safety-view__log-dot--info {
  background: #3b82f6;
}

.safety-view__log-copy {
  flex: 1;
  margin-left: 12px;
}

.safety-view__log-event {
  display: block;
  font-size: 12px;
  font-weight: 600;
  color: #0f172a;
}

.safety-view__log-time {
  display: block;
  margin-top: 4px;
  font-size: 10px;
  color: #94a3b8;
}

@media screen and (min-width: 640px) {
  .safety-view__sensor-grid .card-box {
    width: calc(33.3333% - 12px);
  }
}

@media screen and (min-width: 1024px) {
  .safety-view__sensor-grid .card-box {
    width: calc(25% - 12px);
  }
}

@media screen and (min-width: 1280px) {
  .safety-view__sensor-grid .card-box {
    width: calc(16.6667% - 12px);
  }
}
</style>

// iot-app-dev/src/features/safety/SafetyView.tsx
import React from 'react';
import { AnimatePresence, motion } from 'motion/react';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  CheckCircle2,
  ChevronRight,
  Droplets,
  History,
  ShieldCheck,
  Thermometer,
  User,
  Wind,
} from 'lucide-react';
import { cn } from '../../shared/lib/utils';
import { Device, FirebaseUser } from '../../shared/types';
import { Card } from '../../shared/ui/Card';
import { useSafetyMonitor } from './hooks/useSafetyMonitor';

export const SafetyView = ({
  devices,
  user,
}: {
  devices: Device[];
  user: FirebaseUser | null;
}) => {
  const {
    device,
    myDevices,
    sharedDevices,
    selectedDeviceId,
    setSelectedDeviceId,
    isDropdownOpen,
    setIsDropdownOpen,
    logs,
    alertLogs,
    sensors,
  } = useSafetyMonitor(devices, user);

  if (devices.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center space-y-4 py-20 text-slate-400">
        <ShieldCheck size={48} className="opacity-20" />
        <p className="text-sm">请先添加设备以开启安全监控</p>
      </div>
    );
  }

  const sensorIcons = {
    gas: Droplets,
    smoke: Activity,
    temp: Thermometer,
    human: User,
    vibration: AlertTriangle,
    flow: Wind,
  } as const;

  return (
    <div className="space-y-6 pb-20">
      <div className="flex flex-row items-center justify-between gap-2 px-1">
        <div className="min-w-0 flex-1">
          <h2 className="truncate font-display text-xl font-bold sm:text-3xl">
            安全中心
          </h2>
          <p className="truncate text-[10px] text-slate-500 sm:text-sm">
            实时监控全屋厨房安全
          </p>
        </div>
        {devices.length > 1 && (
          <div className="relative shrink-0">
            <button
              onClick={() => setIsDropdownOpen(!isDropdownOpen)}
              className="flex items-center space-x-1.5 rounded-2xl border border-slate-100 bg-white px-3 py-2 shadow-sm transition-all active:scale-95"
            >
              <span className="max-w-[80px] truncate text-[10px] font-bold text-slate-700 sm:max-w-none sm:text-xs">
                {device?.name}
              </span>
              <ChevronRight
                size={12}
                className={cn(
                  'text-slate-400 transition-transform duration-300',
                  isDropdownOpen ? 'rotate-90' : 'rotate-0'
                )}
              />
            </button>

            <AnimatePresence>
              {isDropdownOpen && (
                <>
                  <div
                    className="fixed inset-0 z-[60]"
                    onClick={() => setIsDropdownOpen(false)}
                  />
                  <motion.div
                    initial={{ opacity: 0, y: 10, scale: 0.95 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, y: 10, scale: 0.95 }}
                    className="absolute right-0 z-[70] mt-2 w-56 overflow-hidden rounded-2xl border border-slate-50 bg-white p-2 shadow-xl"
                  >
                    <div className="max-h-[300px] overflow-y-auto">
                      {myDevices.length > 0 && (
                        <div className="mb-2">
                          <div className="px-3 py-2 text-[10px] font-bold uppercase tracking-widest text-slate-400">
                            我的设备
                          </div>
                          {myDevices.map((currentDevice) => (
                            <button
                              key={currentDevice.id}
                              onClick={() => {
                                setSelectedDeviceId(currentDevice.id);
                                setIsDropdownOpen(false);
                              }}
                              className={cn(
                                'flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-xs font-bold transition-colors',
                                selectedDeviceId === currentDevice.id
                                  ? 'bg-orange-50 text-orange-500'
                                  : 'text-slate-600 hover:bg-slate-50'
                              )}
                            >
                              <span className="mr-2 truncate">
                                {currentDevice.name}
                              </span>
                              {selectedDeviceId === currentDevice.id && (
                                <CheckCircle2 size={14} />
                              )}
                            </button>
                          ))}
                        </div>
                      )}

                      {sharedDevices.length > 0 && (
                        <div>
                          <div className="px-3 py-2 text-[10px] font-bold uppercase tracking-widest text-slate-400">
                            共享设备
                          </div>
                          {sharedDevices.map((currentDevice) => (
                            <button
                              key={currentDevice.id}
                              onClick={() => {
                                setSelectedDeviceId(currentDevice.id);
                                setIsDropdownOpen(false);
                              }}
                              className={cn(
                                'flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-xs font-bold transition-colors',
                                selectedDeviceId === currentDevice.id
                                  ? 'bg-orange-50 text-orange-500'
                                  : 'text-slate-600 hover:bg-slate-50'
                              )}
                            >
                              <span className="mr-2 truncate">
                                {currentDevice.name}
                              </span>
                              {selectedDeviceId === currentDevice.id && (
                                <CheckCircle2 size={14} />
                              )}
                            </button>
                          ))}
                        </div>
                      )}
                    </div>
                  </motion.div>
                </>
              )}
            </AnimatePresence>
          </div>
        )}
      </div>

      <Card
        className={cn(
          'border-0 text-white transition-colors duration-500',
          device?.isOn ? 'bg-emerald-500' : 'bg-slate-700'
        )}
      >
        <div className="flex items-center justify-between">
          <div className="space-y-1">
            <p className="text-[10px] font-medium uppercase tracking-wider text-white/70">
              当前安全评分
            </p>
            <p className="font-display text-4xl font-bold">
              {device?.isOn ? '98' : '--'}
            </p>
          </div>
          <div className="flex h-16 w-16 items-center justify-center rounded-full bg-white/20">
            <ShieldCheck size={32} />
          </div>
        </div>
        <div className="mt-4 flex items-center justify-between border-t border-white/10 pt-4 text-[10px]">
          <span>
            {device?.isOn
              ? '所有传感器运行正常'
              : '设备待机中，基础监测仍保持开启'}
          </span>
          <button className="font-medium underline">查看报告</button>
        </div>
      </Card>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">
        {sensors.map((sensor) => (
          <Card key={sensor.id} className="space-y-3 p-3">
            <div className="flex items-center justify-between">
              {(() => {
                const Icon = sensorIcons[sensor.icon];
                return (
                  <div
                    className={cn(
                      'rounded-lg p-1.5',
                      sensor.status === 'safe'
                        ? 'bg-emerald-50 text-emerald-500'
                        : sensor.status === 'warning'
                        ? 'bg-amber-50 text-amber-500'
                        : 'bg-rose-50 text-rose-500'
                    )}
                  >
                    <Icon size={18} />
                  </div>
                );
              })()}
              <div
                className={cn(
                  'h-2 w-2 rounded-full',
                  sensor.status === 'safe'
                    ? 'bg-emerald-500'
                    : sensor.status === 'warning'
                    ? 'bg-amber-500'
                    : 'bg-rose-500'
                )}
              />
            </div>
            <div>
              <p className="text-[10px] font-medium text-slate-400">
                {sensor.label}
              </p>
              <p className="text-sm font-bold text-slate-900">{sensor.value}</p>
            </div>
          </Card>
        ))}
      </div>

      <Card className="overflow-hidden p-0">
        <div className="flex items-center justify-between border-b border-slate-50 p-4">
          <h3 className="text-sm font-bold">告警记录</h3>
          <AlertCircle size={16} className="text-rose-400" />
        </div>
        <div className="max-h-[200px] divide-y divide-slate-50 overflow-y-auto">
          {alertLogs.length === 0 ? (
            <div className="p-8 text-center text-xs text-slate-400">
              暂无告警记录
            </div>
          ) : (
            alertLogs.map((log) => (
              <div key={log.id} className="flex items-start space-x-3 p-4">
                <div
                  className={cn(
                    'mt-1 h-2 w-2 shrink-0 rounded-full',
                    log.type === 'warning' ? 'bg-amber-500' : 'bg-rose-500'
                  )}
                />
                <div className="space-y-0.5">
                  <p className="text-xs font-medium text-slate-900">{log.event}</p>
                  <p className="text-[10px] text-slate-400">{log.time}</p>
                </div>
              </div>
            ))
          )}
        </div>
      </Card>

      <Card className="overflow-hidden p-0">
        <div className="flex items-center justify-between border-b border-slate-50 p-4">
          <h3 className="text-sm font-bold">操作记录</h3>
          <History size={16} className="text-slate-400" />
        </div>
        <div className="max-h-[200px] divide-y divide-slate-50 overflow-y-auto">
          {logs.length === 0 ? (
            <div className="p-8 text-center text-xs text-slate-400">
              暂无操作记录
            </div>
          ) : (
            logs.map((log) => (
              <div key={log.id} className="flex items-start space-x-3 p-4">
                <div
                  className={cn(
                    'mt-1 h-2 w-2 shrink-0 rounded-full',
                    log.type === 'warning'
                      ? 'bg-amber-500'
                      : log.type === 'success'
                      ? 'bg-emerald-500'
                      : 'bg-blue-500'
                  )}
                />
                <div className="space-y-0.5">
                  <p className="text-xs font-medium text-slate-900">{log.event}</p>
                  <p className="text-[10px] text-slate-400">
                    {log.createdAt
                      ? new Date(log.createdAt).toLocaleString()
                      : '刚刚'}
                  </p>
                </div>
              </div>
            ))
          )}
        </div>
      </Card>
    </div>
  );
};
